### ISSUE TITLE
${OPTIONAL_ARGS} always empty

### ISSUE THREAD

**Issue by leifg** [Osthanes/deployscripts#62]
In an attempt tot solve #61 I wanted to bind a service on my deployment via `OPTIONAL_ARGS="-e CCS_BIND_SRV=MyService"` (this is an undocumented env variable that is used in the scripts.

But whatever I specify, this variable is always empty. This might be a problem of the IBM Delivery Pipeline, but I wanted to know if someone can confirm this problem.

even setting this variable to something like "a" results in this variable being empty in the script.

**Comment by nfritze** [comment]
The OPTIONAL_ARGS variable is set on the delivery pipeline by the field "Optional deploy arguments" from the pipeline, and in tests, that seems to be working.  It's not docced because in our normal use (through that pipeline extension), it will always be overwritten by the contents of that field. 

Are you using this script through the pipeline (in which case, this is normal and expected - just fill in the field), or separately (in which case, this should be working, and seems to be in my testing?

**Comment by leifg** [comment]
I did not see the optional deploy argument field. Tested it, works like a charme. Thanks.

**Comment by nfritze** [comment]
Cool.  Glad to hear it's working - thanks!
